### ISSUE TITLE
Update action by Id

### ISSUE THREAD

**Issue by rcoopr** [bitfocus/companion-module-base#44]
Is it possible to update a single action?

For example, I want an input with 2 dropdown options. The 2nd dropdown choices are dependent on the 1st.
Is it possible to update the 2nd dropdown within the subscribe callback or some such method?

**Comment by dnmeid** [comment]
`setActionsDefinitions()` always pushes the whole object with all actions, currently it is not possible to update only one action and it is also not planned.
For options there is the `isVisible`property where you can pass a function. The options will only be shown when the functions returns true. If your 2nd dropdown choices are nor completely dynamic, this is the common solution.
E.g. first dropdown says 'adjust inputs' or 'adjust outputs'. Then you add one dropdown with all inputs and make it only visible if first dropdown is at inputs and you add another dropdown with all outputs and make it only visible if first dropdown is at outputs.

**Comment by rcoopr** [comment]
I seems to run into issues when the function returns a mix of true or false.
```js
const updateSelectionsNode = {
  name: 'Update Selection Node',
  options: [
  ...selections.map((selection, index) => ({
      type: 'dropdown',
      label: 'Action',
      id: 'value',
      choices: selection.selections,
      default: selection.selections?.[0]?.id,
      isVisible: () => index == 0,
      allowCustom: false,
  })),
}
```

`isVisible: () => false` hides all, `isVisible: () => true` shows all, and a function that should only show 1 shows none

**Comment by rcoopr** [comment]
Also I'm not sure how to get the initial choice on page load with your solution - the subscribe callback isn't called on page load, so where do I get the current state of the 1st dropdown?

**Comment by krocheck** [comment]
@rcoopr I think you're looking for https://github.com/bitfocus/companion/issues/1635, which has not been worked on to my knowledge.

**Comment by dnmeid** [comment]
> `isVisible: () => index == 0,`

Your error is that you compare `index` which is a variable in the context of the action definition.
The way you are doing it right now, the visibility will be controlled by the value of index at the time of defining the action because index will just be replaced with its value at the declaration time.

The function you set isVisible to, is called every time an option changes and is passed all the option values.
look at this example:
```
options: [
  {
    type: 'dropdown',
    label: '1. Option',
    id: 'selection',
    choices: [{id: 1, label: 'Text A'}, {id: 2, label: 'Text B'}],
    default: 1, 
  },
  {
    id: 'textA',
    type: 'static-text',
    label: 'Text',
    value: 'This is text A',
    isVisible: (options) => options.selection === 1
  },
  {
    id: 'textB',
    type: 'static-text',
    label: 'Text',
    value: 'This is text B',
    isVisible: (options) => options.selection === 2
  },
] 
```

The difference is that the argument `options` is passed during runtime with the actual values of your options. You don't have to care about subscribe or unsubscribe. isVisible will be called the first time when the action is added and on every change.

You have a problem though if you don't know all your options and option-ids in advance and the options itself are automatically generated. In that case you don't know the values to compare to and that means you have to generate the function with an eval.
```
  isVisible: new Function( 'options', `return options.${idOfOptionToCompare} === ${valueToCompareTo}`)
```

**Comment by dnmeid** [comment]
> @rcoopr I think you're looking for [bitfocus/companion#1635](https://github.com/bitfocus/companion/issues/1635), which has not been worked on to my knowledge.

Correct, it is the same question. But all of this is doable with isVisible. #1635 is just still open because it evolved to an enhancement request.

**Comment by rcoopr** [comment]
The comparison of `index` was to explain what I believe to be a bug - I'm not expecting it to change, however it always showed all dropdowns, or none. Your code snippet with options as the param is very helpful though, thank you

**Comment by Julusian** [comment]
> Your error is that you compare index which is a variable in the context of the action definition.
> The way you are doing it right now, the visibility will be controlled by the value of index at the time of defining the action because index will just be replaced with its value at the declaration time.

`index` will be unavailable at the time the function is run, so will always be `undefined`. So the function of `() => index == 0` is equivalent to writing `() => undefined == 0`.

----

Expanding on what @dnmeid has said here, `isVisible` is intentionally very limited as it gets run in the browser so that it can react instantly to the user changing the options. It is not able to use any external values other than the `options` parameter it is provided.

**Comment by rcoopr** [comment]
I would have thought the variable remains in the local scope of the function. I'm not sure I see the value in `isVisible` if it can only use the `options` param. 

Still struggling to implement the `new Function` method of toggling the visibility correctly. If I set isVisible as such:
```
isVisible: new Function('options', `console.log(options.controlnode == '${selection.id}')`)
```
This logs `true false`
If I set it to actually return a boolean:
```
isVisible: new Function('options', `return options.controlnode == '${selection.id}'`)
```
Both the options are hidden when one value of the 1ts dropdown is selected, and both visible when the other is selected.

I can try to get a repro sorted tomorrow

**Comment by rcoopr** [comment]
Alright, turns out I was creating multiple dropdowns with the same id, so instead I gave each secondary dropdown an id that matched the 1st dropdowns value. Then the selected value can be found through `action.options[action.options["first-dropdown"]`.


Thanks for the help, found the documentation a little sparse on this

**Comment by Julusian** [comment]
> I would have thought the variable remains in the local scope of the function. I'm not sure I see the value in isVisible if it can only use the options param (in the context of dynamic options).

I can see why you would think that, and I agree that would be useful to do. I haven't tried to make it work, but I am pretty sure this is a technical limitation stopping this from being possible. This is happening because we are serializing these functions and sending them to the ui to be executed, they have to be self contained. The serialization doesn't capture these variables, and if it did that could be problematic (reference `this` and it will try and send a copy of your module to the ui) 
Maybe this can be improved, if someone wants to spend the time to figure out if variable capture is possible, but I suspect it wont be.
